spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.hbm2ddl.auto: update


common:
  datasource:                           # 指定数据源
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authenticated_authorization?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat
    minEvictableIdleTimeMillis: 300000      # 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true

logging:
  level:
    root: INFO
    org.hibernate.sql: debug
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE