spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

common:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_authorization?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize:
      minIdle:
      maxActive:
      maxWait:
      timeBetweenEvictionRunsMillis:
      minEvictableIdleTimeMillis:
      validationQuery: select 1
      testWhileIdle:
      testOnBorrow:
      poolPreparedStatements:
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500